usage: apply this to enforce client verification for valid api call
description: Client verification.
headers:
  client_id:
    description: A valid client_id provided to you by Amgen to access resources.
    required: true
  client_secret:
    description: A valid client_secret for given client_id.
    required: true
